#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.vinapex: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#spring:
#  security:
#    user:
#      name: john.carnell
#      password: password1
#      roles: ADMIN,USER
#security:
#  oauth2:
#    client:
#      client-id: eagleeye
#      client-secret: thisissecret
#      authorized-grant-types: refresh_token,password,client_credentials
#      scope: mobileclient,webclient

server:
  servlet:
    context-path: /auth